#  引言 {.unnumbered}  

本课程是Python入门、数据处理和分析的教程，适用于经管类本科专业。考虑到同学们的计算机基础可能有比较大的差异，因此本课程也兼有编程入门的性质，在基础部分会讲得详细一些。

1. 本课件的网址为[https://py4ss.net/python](https://py4ss.net/python)，需要和课程配套使用。这份讲义每年都会有很大的改写，特别是中后段，同时也会根据教学过程逐步更新。
2. 本课程**要求**带笔记本电脑上课，并在自己的电脑上安装Python环境（后面会有安装教学）

## 关于讲义和教材

1. 不需要购买教材
2. Python作为流行的编程语言，网络资料非常丰富。除了跟班学习之外，也推荐充分利用网络资源，比如搜索引擎（不推荐百度，搜索专业类问题结果比较糟糕，能用谷歌最佳，否则也可以考虑用bing），网课或者各种AI工具。


## 关于AI工具

本课程欢迎以及推荐大家大量使用AI辅助学习。

1. AI工具就像新时代的计算器，行业中已经在大量使用。
2. AI让编程变得前所未有地简单，但前提是你自己要懂，起码要能理解AI给你的结果。
3. 如果你提交一个自己看不懂的作业/成果，你的老师可能放过你，但你的老板肯定不会。

## 本课程的主要内容：

基础部分：

1. Python入门
2. 基础数据处理、绘图和分析
3. 基础统计分析、聚类、线性回归等

专业部分：

1. 通用类：投资-现金流关系（真实数据处理和实证分析流程）
2. 金融类：CAPM和FF3因子模型（时间序列处理和多因子模型）、最优组合（数值方法如插值、最优化和解方程，以及蒙特卡洛模拟）、量化技术分析和交易策略初步（重写中）

其他：看教学情况适时调整。


## 上课形式

1. 课堂讲解
2. ★ 课堂作业

## 考察形式

1. 30%平时分，70%期末考察
2. 期末考察的形式是编程大作业，包括编程的基础、一般性的算法题和专业相关的分析题


## 考虑增补的内容：
:::{.callout-warning}

1. 字符串专题 + 正则表达式
2. 面向对象进阶 + 简单设计模式
3. 爬虫入门 (技术路线太长)
4. (✓) CAPM，最优组合，简单量化交易 
5. Python和Excel相互操作。
6. 更多的案例 (★)
:::